# This is a basic workflow to help you get started with Actions

name: Publish HPC App Binaries

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
    paths:
    - 'hpc-application/**'    
  pull_request:
    branches: [ main ]
    paths:
    - 'hpc-application/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Runs print env
      - name: Run a one-line script
        run: printenv

      # Runs a set of commands using the runners shell
      - name: Archive HPC app
        run: |
          mkdir package
          pushd hpc-application
          zip -r ../package/${{ github.sha }}.zip ./ffmpeg-3.4-win64-static
          popd
          ls
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          mkdir temp
          unzip -qq package/${{ github.sha }}.zip -d ./temp
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          pwd
          ls temp/ffmpeg-3.4-win64-static

